export let kazuma: string[] = [];

kazuma.push("I hate this damned language!");
kazuma.push("You didn't let me defend you ten days ago. I know your intentions are good, however... I want to at least finish off what you started with my own hands.");
kazuma.push("Ah hah hah hah hah!");
kazuma.push("You had me really worried for a second there... Honestly.");
kazuma.push("Come again?");
kazuma.push("What's wrong Naruhodou? This is no time to be day-dreaming!");
kazuma.push("Of course, it's a choice, but you... Don't even know what the Randst Magazine is.");
kazuma.push("I realise you're in charge now, but still... Try not to look so bewildered.");
kazuma.push("Swish swish..?");
kazuma.push("In court, when you're backed into a corner and you have nowhere left to turn.. It's hard to keep believing in what you must believe in.");
kazuma.push("I see. My apologies. We should get going now.");
kazuma.push("Naruhodou! Is there anyone that trusts you more than me? Leave it to me! All you have to do is trust me.");
kazuma.push("We can't fraternize anymore.");
kazuma.push("The court is the place where we should clarify the truth. For this reason, I intend to share what I know.");
kazuma.push("If you keep spouting nonsense, the next thing you will eat is my knuckle sandwich. I've heard it's got a nice, chewy consistency.");
kazuma.push("Mull it over and try again. Do it before the judge strikes you with his gavel.");
kazuma.push("Don’t sulk like that. Lift your head. Straighten your back. Face forward and don’t avert your eyes from the truth. If it’s you we’re talking about, then you can cut down any kind of fortune. …That’s what I believe.");
kazuma.push("...The truth please.");
kazuma.push("Honestly, you never change at all. But that's what I like about you.");
kazuma.push("I'm so sorry, Naruhodou..");
kazuma.push("I knew it! You ordered these witnesses to lie under oath!");
kazuma.push("Today, you... believed in me until the end, even though I am naught but a mere student. Though you had crisis after crisis thrust upon you, not once did you avert your gaze.");
kazuma.push("Sounds more like a malediction than a contradiction to me, partner.");
kazuma.push("If that position has the authority of the police backing it, it seems like that person would have the power to be coercive.");
kazuma.push("How will apologizing to me accomplish anything?");
kazuma.push("It was a personal request. I asked to be assigned to the trial.");
kazuma.push("Naruhodou... You seem like the kind of guy who studies just because his parents tell him to.");
kazuma.push("It would bring me great pleasure to rampage through the Queen's domain with you.");
kazuma.push("Just don't forget you owe me a extra large beef hotpot from Yuumei Cafeteria.");
kazuma.push("How much joy would you and I have rampaging the streets of Her Majesty the Queen's fair land?");
kazuma.push("Those who punish others bear a responsibility for their choices. That should be their resolve.");
kazuma.push("Anyway, just try your best, Ace Attorney!");
kazuma.push("A gunshot rang out from nearby, right?");
kazuma.push("No matter how sleepy you are, there's no way you would have forgotten that.");
kazuma.push("You could well call this my reason for living over the past ten years!");
kazuma.push("However, that is impossible. I don't need to spell it out for you, do I? I didn't cut a single hair on your head, Ergo! You should be able to tie one of your beloved topknots!");
kazuma.push("Ah.. Do pardon my manners, my lady.");
kazuma.push("Well said, Naruhodou. Even if your eyes were darting around the whole time.");
kazuma.push("It's covered in meat sauce.");
kazuma.push("I'm sure you're curious... about how we were created, no?");
kazuma.push("Don't call me 'partner' after coming out with nonsense like that!");
kazuma.push("Your testimony just now is what you call the “truth”?");
kazuma.push("Until the conclusion of today's trial when a final verdict is handed down... No one may refer to this man as a criminal.");
kazuma.push("Of course, say it loud and clear, Ryuunosuke Naruhodou!");
kazuma.push("Naruhodou, the truth is, there is something I must discuss with you...");
kazuma.push("You're too kind.");
kazuma.push("W-Who else? It's just me and you in this room. By the way, it is nearly time for dinner. Do you mind if we resume our talk afterwards?");
kazuma.push("Don't give me that “Thats true.” garbage. You should be capable of remembering a measly three digits!");
kazuma.push("Isn't that so, Naruhodou-san?");
kazuma.push("Show me what you can do! Time for a great turnabout!");
kazuma.push("Well, Naruhodou? Did you find it?");
kazuma.push("Yes, I've finally done it! it feels like a dream come true.");
kazuma.push("W-What?!");
kazuma.push("(But my friend has been in that wardrobe for more than a week. Is he even human..?)");
kazuma.push("...Enough already.");
kazuma.push("What?! It was “ama-ka-”.. ARGHHHHHGH!!!");
kazuma.push("I can hardly believe it. I mean, just look at you. Drenched in sweat, knees trembling, eyes darting, teeth chattering. But even in that sorry state, you still managed to grasp the truth.");
kazuma.push("This night has ended. We'll see you again tomorrow evening.");
kazuma.push("It'll all become clear tomorrow.");
kazuma.push("I apologize for my actions. I won't do it again.");
kazuma.push("You did it, partner!");
kazuma.push("By the way... Did you ever find that koban?");
kazuma.push("You sure have a lot of hatred heaped on you, don't you?");
kazuma.push("Just don't forget you owe me a extra large beef hotpot from Yuumei Cafeteria.");
kazuma.push("......... How sad. It means you don't have faith in me. You think I won't be able to get you off.")
